# Generated by Django 4.2.16 on 2024-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
